# @format

input XUID {
  xuid: ID
}

input Gamertag {
  gamertag: String
}
type XboxError {
  Error: String
}
union Result = XboxError | Friend
type Query {
  friendsList(member: Gamertag!): [Result]
}
